// client/src/routes/(authorization)/login/+page.svelte
<script>
	import Logo from '$lib/assets/icons/aniflix-logo-large.png';
	import LoginBackground from '$lib/assets/images/aniflix-login.png';
	import LoginCard from '$lib/components/login/login-card.svelte';
	import RegisterCard from '$lib/components/login/register-card.svelte';
	import {Tabs, TabsContent, TabsList, TabsTrigger} from '$lib/components/ui/tabs';
</script>

<div class="container relative grid h-screen flex-col items-center justify-center lg:max-w-none lg:grid-cols-2 lg:px-0">
	<div class="bg-muted relative hidden h-full flex-col p-10 text-white lg:flex dark:border-r">
		<div class="absolute inset-0 min-h-screen min-w-full">
			<img
				src={LoginBackground}
				alt={'Authentication'}
				width={7680}
				height={4320}
				class="h-full overflow-hidden object-cover brightness-[0.35]"
				priority
			/>
		</div>

		<div class="relative z-20 flex items-center text-lg font-medium">
			<svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
				class="mr-2 h-6 w-6"
			>
				<path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3" />
			</svg>
			Aniflix.stream
		</div>

		<div class="relative z-20 mt-auto">
			<blockquote class="space-y-2">
				<p class="text-lg">&ldquo;Ill find a good quote to put here.&rdquo;</p>
				<footer class="text-sm">The Developer</footer>
			</blockquote>
		</div>
	</div>
	<div class="lg:p-8 ">
		<div class="mx-auto flex w-[350px] flex-col justify-center space-y-6">
			<div class="px-16">
				<img src={Logo} alt="AniFlix Logo" width={941} height={313} priority />
			</div>
			<Tabs defaultValue="login">
				<TabsList class="w-full">
					<TabsTrigger class="w-[50%] text-center" value="login">Login</TabsTrigger>
					<TabsTrigger class="w-[50%] text-center" value="register">Register</TabsTrigger>
				</TabsList>
				<TabsContent value="login">
					<LoginCard />
				</TabsContent>
				<TabsContent value="register">
					<RegisterCard />
				</TabsContent>
			</Tabs>
			<p class="text-muted-foreground px-8 text-center text-sm">
				By clicking continue, you agree to our{' '}
				<a href="/terms" class="hover:text-primary underline underline-offset-4"> Terms of Service </a>{' '}
				and{' '}
				<a href="/privacy" class="hover:text-primary underline underline-offset-4"> Privacy Policy </a>
				.
			</p>
		</div>
	</div>
</div>

// frontend/pages/login/index.tsx


import LoginForm from "@components/login/LoginForm";
import RegisterForm from "@components/login/RegisterForm";
import VerificationButton from "@components/login/VerificationButton";
import {useIsAuthenticated} from "@hooks/useIsAuthenticated";
import AniFlixLogo from "@icons/AniFlixLogo";
import GithubSignIn from "@icons/GithubSignIn";
import GoogleSignIn from "@icons/GoogleSignIn";
import LoginBackground from "@images/aniflix-login.png";


import React, {useState} from "react";

import Image from "next/image";
import Link from "next/link";

export default function Login() {
    const {isSignedIn, isVerified} = useIsAuthenticated();
    const [register, setRegister] = useState<boolean>(false);
    
    return (
        <div className={"h-full w-full max-w-[550px] mx-auto flex justify-center items-center"}>
            <div className={"absolute top-0 left-0 w-full h-full brightness-75 -z-10"}>
                <Image
                    src={LoginBackground}
                    alt={"Login Background"}
                    width={7680}
                    height={4320}
                    className={"min-h-screen h-full object-cover overflow-hidden"}
                    priority
                />
            </div>
            
            <div className={"flex items-center min-h-[100vh] w-full p-[5%]"}>
                <div className={"bg-black/90 flex flex-col w-full p-10 mb-8 rounded-lg"}>
                    <div className={"flex flex-col items-center space-y-6 mb-6"}>
                        <AniFlixLogo className={"w-[50%] h-[50%}"}/>
                        
                        {!isSignedIn && (register
                            ? <h4 className={"font-poppins text-xl text-white"}> Register Account </h4>
                            : <h4 className={"font-poppins text-xl text-white"}> Sign-In </h4>)
                        }
                        
                        {(isSignedIn && !isVerified)
                            ? <VerificationButton/>
                            : register ? <RegisterForm/> : <LoginForm/>
                        }
                        
                        {!isSignedIn &&
                            <div className={"font-poppins text-white flex space-x-2"}>
                                <span className={"interactive-underline cursor-pointer"} onClick={() => setRegister(false)}>Sign-in</span>
                                <span> - </span>
                                <span className={"interactive-underline cursor-pointer"} onClick={() => setRegister(true)}>Register</span>
                            </div>
                        }
                        
                        <div className={"flex flex-col items-center space-y-4 w-full"}>
                            <div className={"w-[80%] h-[1px] bg-[#717171]"}/>
                            <div className={"flex flex-col space-y-4 w-full px-14 items-center"}>
                                <div className={"flex flex-row items-center space-x-4 pb-2"}>
                                    <p className={"text-[#717171] font-poppins text-xs cursor-default"}>
                                        <span> or sign in with </span>
                                    </p>
                                </div>
                                <GoogleSignIn/>
                                <GithubSignIn/>
                                <div className={"flex flex-row items-center space-x-4 pt-10"}>
                                    <Link className={"text-[#717171] font-poppins text-xs interactive-underline"}
                                       href={"https://github.com/Jordi-Jaspers"}>
                                        © Designed and built by Jordi Jaspers
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
