// client/src/lib/components/app/footer/footer.svelte
<script lang="ts">
let applicationVersion = __VERSION__;
let applicationName = __NAME__;
</script>

<footer class="px-[4%] py-10 text-center text-xs text-muted-foreground">
	<div>
		<span>{applicationVersion}</span>
		<span>|</span>
		<span>{applicationName}</span>
		<span>|</span>
		<a href="https://github.com/Jordi-Jaspers" target="_blank" class="hover:underline"> © Jordi Jaspers 2024, All rights reserved.</a>
	</div>
</footer>

// backup/client/src/components/footer/Footer.tsx
import React from "react";

import Link from "next/link";

export default function Footer() {
    return (
        <footer className={"flex flex-row items-center justify-center p-8 w-full bg-[#1a1920]"}>
            <Link className={"font-poppins text-[#d1d1d1]"} href={"https://github.com/Jordi-Jaspers"}>
                © Designed and built by Jordi Jaspers
            </Link>
        </footer>
    )
}
