// client/src/lib/components/app/header/header.svelte
<script lang="ts">
	import Logo from '$lib/assets/icons/aniflix-logo-large.png';
	import SearchBar from '$lib/components/app/header/search-bar.svelte';
	import UserButton from '$lib/components/app/header/user-button.svelte';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { LightSwitch } from '$lib/components/general/index.js';
	import { Badge } from '$lib/components/ui/badge';

	let currentPath = '';
	$: currentPath = $page.url.pathname;

	let isScrolled: boolean = false;
	onMount(() => {
		const handleScroll = () => {
			isScrolled = window.scrollY > 0;
		};
		window.addEventListener('scroll', handleScroll);
		return () => {
			window.removeEventListener('scroll', handleScroll);
		};
	});
</script>

<header
	class="sticky top-0 !z-50 flex h-[5vw] max-h-[75px] min-h-[60px] w-full flex-row items-center justify-between overflow-hidden px-[4%] transition-colors duration-300 lg:px-[60px] {isScrolled
		? 'bg-background/80'
		: 'bg-transparent bg-gradient-to-b from-background to-transparent'}"
>
	<div class="flex flex-row items-center space-x-4">
		<div class="flex items-center space-x-1">
			<img alt="AniFlix Logo" class="h-full max-h-[32px]" src={Logo} />
			{#if import.meta.env.VITE_ENV !== 'production'}
				<Badge variant="outline" class="my-3 bg-green-600">TST</Badge>
			{/if}
		</div>

		<div class="hidden flex-row space-x-4 text-xs font-light md:flex">
			<a class={currentPath.includes('/browse') ? 'font-bold' : ''} href="/browse">Browse</a>
			<a class={currentPath.includes('/news') ? 'font-bold' : ''} href="/news">News</a>
			<a class={currentPath.includes('/library') ? 'font-bold' : ''} href="/library">Library</a>
		</div>
	</div>

	<div class="flex h-full flex-row items-center md:space-x-2">
		<SearchBar />
		<LightSwitch />
		<UserButton />
	</div>
</header>

// frontend/components/Header.tsx
import BasicMenu from "@components/BasicMenu";
import {BellIcon} from '@heroicons/react/24/outline';
import {MagnifyingGlassIcon} from '@heroicons/react/24/solid';
import AniFlixLogo from "@icons/AniFlixLogo";
import Image from "next/image";
import Link from 'next/link'
import {useEffect, useState} from 'react'

export default function Header() {
    const [isScrolled, setIsScrolled] = useState(false)
    useEffect(() => {
        const handleScroll = () => {
            if (window.scrollY > 0) {
                setIsScrolled(true)
            } else {
                setIsScrolled(false)
            }
        }
        window.addEventListener('scroll', handleScroll)
        return () => {
            window.removeEventListener('scroll', handleScroll)
        }
    }, [])
    
    return (
        <header
            className={`sticky top-0 z-[100] h-[70px] w-screen flex flex-row justify-between pl-4 pr-4 md:pl-6 md:pr-6 lg:pl-12 lg:pr-12
            bg-gradient-to-b from-[#141414] to-transparent transition-colors duration-300
            ${isScrolled ? 'bg-[#141414]/80' : 'bg-transparent'}`}>
            <div className="flex flex-row items-center space-x-2 md:space-x-10 h-16">
                <AniFlixLogo className={"cursor-pointer object-contain w-fit h-[2em]"}/>
                <BasicMenu/>
                
                <ul className="hidden space-x-4 md:flex">
                    <li className="headerLink cursor-default font-semibold text-white hover:text-white">
                        Home
                    </li>
                    <li className="headerLink">TV Shows</li>
                    <li className="headerLink">Movies</li>
                    <li className="headerLink">Trending</li>
                    <li className="headerLink">New & Popular</li>
                    <li className="headerLink">Recently Added</li>
                </ul>
            </div>
            <div className="flex flex-row items-center space-x-6 text-sm font-poppins">
                {/* TODO: ALL this... */}
                <MagnifyingGlassIcon className="headerIcon"/>
                <BellIcon className="headerIcon"/>
                <Link href="">
                    <Image
                        src="https://rb.gy/g1pwyx"
                        alt="Profile Picture"
                        className="cursor-pointer rounded"
                        width={32}
                        height={32}
                    />
                </Link>
            </div>
        </header>
    )
}
