// frontend/components/header/search/SearchBar.tsx
import {searchResultsState, showSearchResultsState} from "@atoms/SearchResultScreen";
import AnimeService from "@consumet/AnimeService";
import {MagnifyingGlassIcon} from "@heroicons/react/24/solid";
import React, {useEffect, useRef, useState} from "react";
import {useSetRecoilState} from "recoil";

const SearchBar = () => {
    const [isExpanded, setExpanded] = useState(false);
    const [searchTerm, setSearchTerm] = useState("");
    const inputElement = useRef<HTMLInputElement>(null);
    const setShowSearchResults = useSetRecoilState(showSearchResultsState);
    const setSearchResults = useSetRecoilState(searchResultsState);
    
    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        console.debug(e.key)
        if (e.key === "Escape") {
            setSearchTerm("");
            setExpanded(false);
        }
    }
    
    const handleFocus = () => {
        if (!inputElement.current) return;
        setExpanded(!isExpanded)
        inputElement.current.focus();
    }
    
    useEffect(() => {
        if (isExpanded) {
            setSearchTerm("");
        }
    }, [isExpanded]);
    
    useEffect(() => {
        if (searchTerm.length > 0) {
            setShowSearchResults(true);
            AnimeService.searchAnime(searchTerm).then((res) => {
                setSearchResults(res);
            });
        } else {
            setSearchResults([]);
            setShowSearchResults(false);
        }
    }, [searchTerm]);
    
    return (
        <div className="relative flex flex-row items-center space-x-4">
            <input
                className={`${
                    isExpanded
                        ? "ease-out duration-500 w-48 mt-1 p-2 rounded border border-gray-400 transition-all"
                        : "w-0 ease-in duration-500"
                } bg-[#181818]/80 font-poppins text-sm`}
                onChange={(e) => setSearchTerm(e.target.value)}
                value={searchTerm}
                type="text"
                placeholder="Search"
                onKeyDown={(e) => handleKeyDown(e)}
                ref={inputElement}
            />
            <MagnifyingGlassIcon className="headerIcon" onClick={() => handleFocus()}/>
        </div>
    );
};

export default SearchBar;

// client/src/lib/components/app/header/search-bar.svelte
<script lang="ts">
	import { Search } from 'lucide-svelte';
	import Input from '$lib/components/ui/input/input.svelte';

	let searchTerm: string | null;
	let isOpen: boolean = false;

	function closeSearchBar() {
		const input = document.getElementById('search-bar') as HTMLInputElement;
		if (input) {
			input.blur();
			isOpen = false;
		}
	}

	function openSearchBar() {
		const input = document.getElementById('search-bar') as HTMLInputElement;
		if (input) {
			input.focus();
			isOpen = true;
		}
	}

	function handleEscape(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			closeSearchBar();
		}
	}

	function toggleSearchBar() {
		if (isOpen) {
			closeSearchBar();
		} else {
			openSearchBar();
		}
	}
</script>

<div class="flex flex-row items-center">
	<Input
		id="search-bar"
		class="h-6 mr-1 {isOpen ? 'w-36 transition-all duration-500 ease-out sm:w-48 bg-black' : 'w-0 border-0 duration-500 ease-in'}"
		placeholder="Search"
		bind:value={searchTerm}
		on:keydown={handleEscape}
	/>
	<button on:click={toggleSearchBar} class="items-center flex justify-center">
		<Search />
	</button>
</div>
